<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 static/bulb.gltf
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import FakeGlowMaterial from '../FakeGlowMaterial.js';

	export const ref = new Group();

	export let bloomPass = false;

	//   const fakeGlowMaterial = new FakeGlowMaterial({
	//     falloff: 0.05,
	//     glowInternalRadius: 1.92,
	//     glowSharpness: 0.78,
	//     opacity: 1,
	//     depthTest: true,
	// });

	const gltf = useGltf('bulb.gltf');

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		{#if !bloomPass}
			<T.Group position={[0, 0.19, 0]} scale={0.125}>
				<T.Group position={[0, -1.34, 0]} rotation={[0, Math.PI / 2, 0]} scale={[4.79, 5.16, 4.79]}>
					<T.Mesh
						geometry={gltf.nodes['bombillo-roscadata002'].geometry}
						material={gltf.materials.metal_cobrizo}
					/>
					<T.Mesh
						geometry={gltf.nodes['bombillo-roscadata002_1'].geometry}
						material={gltf.materials.metal_plateado_rugoso}
					/>
					<T.Mesh
						geometry={gltf.nodes['bombillo-roscadata002_2'].geometry}
						material={gltf.materials.negro_pulido}
					/>
				</T.Group>
				<T.Mesh
					geometry={gltf.nodes.Chain.geometry}
					material={gltf.materials.Metal047B}
					position={[0, -0.71, 0]}
					scale={7.62}
				>
					<T.Mesh
						geometry={gltf.nodes.Socket.geometry}
						material={gltf.materials.Plastic006}
						position={[0, -0.08, 0]}
						rotation={[0, Math.PI / 2, 0]}
						scale={0.69}
					>
						<T.Mesh
							geometry={gltf.nodes.Switch.geometry}
							material={gltf.materials.Plastic006}
							position={[-0.01, 0, 0.03]}
							rotation={[Math.PI / 2, 0, 0.5]}
							scale={0.36}
						/>
					</T.Mesh>
				</T.Mesh>
				<T.Mesh
					geometry={gltf.nodes.Filament_1.geometry}
					material={gltf.materials['Emission Material (Must be Done manually in threejs)']}
					position={[0.01, -1.72, 0]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={0.07}
				>
					<T.MeshStandardMaterial
						color="#dd290f"
						emissive={'#dd4c0f'}
						emissiveIntensity={15}
						roughness={0.0}
					/>
					<T.Mesh
						geometry={gltf.nodes.Filament_2.geometry}
						position={[0, -0.27, 0.1]}
						rotation={[-Math.PI, 0, 0]}
					>
						<T.MeshStandardMaterial
							color="#dd4c0f"
							emissive={'#dd4c0f'}
							emissiveIntensity={15}
							roughness={0.0}
						/>
					</T.Mesh>
				</T.Mesh>
				<!-- Glass Bubble -->
				<T.Mesh
					geometry={gltf.nodes.Glass.geometry}
					position={[0, -1.72, 0]}
					rotation={[0, Math.PI / 2, 0]}
					scale={4.57}
				>
					<T.MeshPhysicalMaterial
						color="#ffffff"
						emissive={'#ffffff'}
						emissiveIntensity={0}
						roughness={0}
						transmission={1.0}
						ior={1}
						thickness={0.001}
						specularIntensity={1.0}
					/>
				</T.Mesh>
				<T.Mesh
					geometry={gltf.nodes.Non_emisive.geometry}
					material={gltf.materials.vidrio}
					position={[0, -1.67, 0]}
					rotation={[0, Math.PI / 2, 0]}
					scale={4.57}
				>
					<T.MeshPhysicalMaterial
						color="#ffffff"
						roughness={0}
						transmission={1.0}
						ior={1.9}
						thickness={0.01}
						specularIntensity={1.0}
					/>
					<T.Mesh
						geometry={gltf.nodes.Filament_connection.geometry}
						material={gltf.materials.metal_cobrizo}
						position={[0.00375, 0.035, -0.007]}
						rotation={[Math.PI / 2, -1.57, 0]}
						scale={0.01}
					/>
					<T.Mesh
						geometry={gltf.nodes.Filament_connection2.geometry}
						material={gltf.materials.metal_cobrizo}
						position={[-0.00375, 0.035, 0.007]}
						rotation={[-Math.PI / 2, Math.PI / 2, 0]}
						scale={0.01}
					/>
					<T.Mesh
						geometry={gltf.nodes.Filament_Head.geometry}
						material={gltf.materials.Metal047B}
						position={[0.0045, 0.0235, -0.01]}
						rotation={[Math.PI / 2, -1.8, 0]}
						scale={0.01}
					/>
					<T.Mesh
						geometry={gltf.nodes.Filament_Head2.geometry}
						material={gltf.materials.Metal047B}
						position={[-0.006, 0.0235, 0.01275]}
						rotation={[-Math.PI / 2, Math.PI / 2, 0]}
						scale={0.01}
					/>
				</T.Mesh>
			</T.Group>
		{:else}
			<T.Group position={[0, 0.19, 0]} scale={0.125}>
				<T.Mesh
					geometry={gltf.nodes.Filament_1.geometry}
					material={gltf.materials['Emission Material (Must be Done manually in threejs)']}
					position={[0.01, -1.72, 0]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={0.07}
				>
					<T.MeshPhysicalMaterial
						color="#d4af37"
						roughness={0.0}
						transparent={true}
						opacity={0.7}
						transmission={1.0}
						ior={1.75}
						thickness={1.0}
						specularIntensity={1.0}
					/>
					<T.Mesh
						geometry={gltf.nodes.Filament_2.geometry}
						position={[0, -0.27, 0.1]}
						rotation={[-Math.PI, 0, 0]}
					>
						<T.MeshPhysicalMaterial
							color="#d4af37"
							roughness={0}
							transparent={true}
							opacity={0.7}
							transmission={1.0}
							ior={1.75}
							thickness={1.0}
							specularIntensity={1.0}
						/>
					</T.Mesh>
				</T.Mesh>
			</T.Group>
		{/if}
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
